'use client';

import React, { useState, useEffect } from 'react';
import { 
  Users, 
  Repeat, 
  Wallet, 
  TrendingUp, 
  Target, 
  ShieldCheck,
  AlertTriangle,
  Infinity,
  ArrowRight,
  PieChart,
  Crown,
  Rocket,       // NEW
  BarChart4,    // NEW
  Microscope    // NEW
} from 'lucide-react';

export default function LTVCalculator() {
  // --- STATE: CUSTOMER BEHAVIOR ---
  const [aov, setAov] = useState<number>(1500); // Average Order Value
  const [purchaseFreq, setPurchaseFreq] = useState<number>(4); // Purchases per year
  const [lifespan, setLifespan] = useState<number>(2); // Years they stay
  const [profitMargin, setProfitMargin] = useState<number>(25); // Net margin % per order

  // --- STATE: ACQUISITION COSTS ---
  const [cac, setCac] = useState<number>(500); // Cost to Acquire Customer (Ad Spend)
  
  // --- STATE: SCALING (NEW) ---
  const [monthlyAdBudget, setMonthlyAdBudget] = useState<number>(50000); // How much you spend to scale

  // --- STATE: OUTPUTS ---
  const [metrics, setMetrics] = useState({
    grossLTV: 0,      // Total Revenue per customer
    netLTV: 0,        // Total Profit per customer (Lifetime)
    ltvCacRatio: 0,   // The Golden Ratio
    paybackOrder: 0,  // Which order number pays off the ad spend?
    maxSafeCac: 0,    // How much CAN you spend?
    
    // NEW SCALING METRICS
    acquiredCustomers: 0,
    cohortRevenue: 0,     // Revenue generated by one month's batch of customers over their life
    cohortProfit: 0,      // Profit generated by one month's batch
    roiPercentage: 0,
    
    // SENSITIVITY
    impactAov: 0,         // Profit if AOV +10%
    impactFreq: 0,        // Profit if Freq +10%

    status: 'Unhealthy' as 'Unhealthy' | 'Scale' | 'Star'
  });

  // --- ENGINE ---
  useEffect(() => {
    // 1. Lifetime Value Calculation
    const totalRevenue = aov * purchaseFreq * lifespan;
    const lifetimeProfit = totalRevenue * (profitMargin / 100);

    // 2. The Golden Ratio (LTV:CAC)
    const ratio = cac > 0 ? lifetimeProfit / cac : 0;

    // 3. Payback Period
    const profitPerOrder = aov * (profitMargin / 100);
    const payback = profitPerOrder > 0 ? Math.ceil(cac / profitPerOrder) : 99;

    // 4. Max Safe CAC (Aiming for 3:1 ratio)
    const safeCac = lifetimeProfit / 3;

    // 5. NEW: Scaling Logic (Cohort Analysis)
    const newCustomers = cac > 0 ? Math.floor(monthlyAdBudget / cac) : 0;
    const cohortTotalRev = newCustomers * totalRevenue;
    const cohortTotalProfit = (newCustomers * lifetimeProfit) - monthlyAdBudget; // Net profit after ad spend
    const cohortRoi = monthlyAdBudget > 0 ? (cohortTotalProfit / monthlyAdBudget) * 100 : 0;

    // 6. NEW: Sensitivity Logic (Power of +10%)
    // What if AOV increases 10%?
    const aovBoostLTV = (aov * 1.1) * purchaseFreq * lifespan * (profitMargin / 100);
    // What if Frequency increases 10%?
    const freqBoostLTV = aov * (purchaseFreq * 1.1) * lifespan * (profitMargin / 100);

    // 7. Status Logic
    let status: 'Unhealthy' | 'Scale' | 'Star' = 'Unhealthy';
    if (ratio >= 5) status = 'Star';
    else if (ratio >= 3) status = 'Scale';

    setMetrics({
      grossLTV: totalRevenue,
      netLTV: lifetimeProfit,
      ltvCacRatio: ratio,
      paybackOrder: payback,
      maxSafeCac: safeCac,
      acquiredCustomers: newCustomers,
      cohortRevenue: cohortTotalRev,
      cohortProfit: cohortTotalProfit,
      roiPercentage: cohortRoi,
      impactAov: aovBoostLTV - lifetimeProfit,
      impactFreq: freqBoostLTV - lifetimeProfit,
      status
    });

  }, [aov, purchaseFreq, lifespan, profitMargin, cac, monthlyAdBudget]);

  const fmt = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans p-6 md:p-12">
      <div className="max-w-7xl mx-auto">
        
        {/* HEADER */}
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 mb-10 border-b border-slate-800 pb-8">
          <div>
            <h1 className="text-3xl font-bold text-white flex items-center gap-3">
              <Infinity className="w-8 h-8 text-purple-500" />
              LTV & CAC Architect
            </h1>
            <p className="text-slate-400 mt-2">
              Stop optimizing for the first sale. Optimize for the Customer Lifetime.
            </p>
          </div>
          
          <div className="flex items-center gap-3 bg-slate-900 px-5 py-3 rounded-xl border border-slate-800">
             <Target className="w-6 h-6 text-indigo-500" />
             <div>
                <p className="text-[10px] uppercase font-bold text-slate-500">LTV:CAC Ratio</p>
                <div className={`text-xl font-black ${
                    metrics.status === 'Star' ? 'text-yellow-400' : 
                    metrics.status === 'Scale' ? 'text-emerald-400' : 'text-red-400'
                }`}>
                    {metrics.ltvCacRatio.toFixed(1)}x
                </div>
             </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mb-16">
          
          {/* --- LEFT: CONFIG (4 Cols) --- */}
          <div className="lg:col-span-4 space-y-6">
            
            {/* 1. Customer Behavior */}
            <div className="bg-slate-900 rounded-xl border border-slate-800 p-6">
               <h3 className="text-white font-bold flex items-center gap-2 mb-4">
                  <Users className="w-4 h-4 text-purple-400" /> Behavior Profile
               </h3>
               
               <div className="space-y-4">
                  <div>
                     <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Average Order Value (AOV)</label>
                     <input type="number" value={aov} onChange={e => setAov(Number(e.target.value))} className="w-full bg-slate-950 border border-slate-700 rounded p-2 text-white font-mono font-bold focus:border-purple-500 outline-none" />
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4">
                     <div>
                        <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Orders / Year</label>
                        <input type="number" value={purchaseFreq} onChange={e => setPurchaseFreq(Number(e.target.value))} className="w-full bg-slate-950 border border-slate-700 rounded p-2 text-white text-sm focus:border-purple-500 outline-none" />
                     </div>
                     <div>
                        <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Lifespan (Yrs)</label>
                        <input type="number" value={lifespan} onChange={e => setLifespan(Number(e.target.value))} className="w-full bg-slate-950 border border-slate-700 rounded p-2 text-white text-sm focus:border-purple-500 outline-none" />
                     </div>
                  </div>

                  <div>
                     <div className="flex justify-between mb-1">
                        <label className="text-xs font-bold text-slate-500 uppercase">Net Margin %</label>
                        <span className="text-xs text-white font-bold">{profitMargin}%</span>
                     </div>
                     <input type="range" min="5" max="80" step="1" value={profitMargin} onChange={e => setProfitMargin(Number(e.target.value))} className="w-full accent-purple-500" />
                  </div>
               </div>
            </div>

            {/* 2. Acquisition Cost */}
            <div className="bg-slate-900 rounded-xl border border-slate-800 p-6">
               <h3 className="text-white font-bold flex items-center gap-2 mb-4">
                  <Wallet className="w-4 h-4 text-emerald-400" /> Acquisition
               </h3>
               <div className="space-y-4">
                   <div>
                       <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Current CAC (Ad Spend/Sale)</label>
                       <input type="number" value={cac} onChange={e => setCac(Number(e.target.value))} className="w-full bg-slate-950 border border-slate-700 rounded p-3 text-white font-mono text-lg focus:border-emerald-500 outline-none" />
                   </div>
                   
                   {/* NEW: Scaling Budget Input */}
                   <div className="pt-4 border-t border-slate-800">
                       <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Monthly Ad Budget</label>
                       <input type="number" value={monthlyAdBudget} onChange={e => setMonthlyAdBudget(Number(e.target.value))} className="w-full bg-slate-950 border border-slate-700 rounded p-2 text-white text-sm focus:border-emerald-500 outline-none" />
                       <p className="text-[10px] text-slate-500 mt-1">Used to forecast cohort value.</p>
                   </div>
               </div>
            </div>

          </div>

          {/* --- RIGHT: INTELLIGENCE PANEL (8 Cols) --- */}
          <div className="lg:col-span-8 space-y-6">
            
            {/* 1. LTV Dashboard */}
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 relative overflow-hidden shadow-2xl">
               <div className="relative z-10 flex flex-col md:flex-row justify-between items-start gap-8">
                  <div>
                      <h2 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-2">Lifetime Net Profit</h2>
                      <div className="flex items-baseline gap-2">
                          <span className="text-6xl font-black text-white">
                              {fmt(metrics.netLTV)}
                          </span>
                          <span className="text-sm text-slate-500">per customer</span>
                      </div>
                      <p className="text-xs text-emerald-400 mt-2 font-bold">
                          Gross Revenue: {fmt(metrics.grossLTV)}
                      </p>
                  </div>
                  
                  {/* Ratio Gauge */}
                  <div className="bg-slate-950 p-6 rounded-xl border border-slate-800 w-full md:w-72">
                      <h3 className="text-xs font-bold text-slate-500 uppercase mb-4 text-center">Health Check (Target greater then 3.0x)</h3>
                      
                      <div className="relative h-4 bg-slate-800 rounded-full w-full overflow-hidden">
                          <div 
                             className={`h-full transition-all duration-700 ${
                                 metrics.status === 'Star' ? 'bg-yellow-400' : 
                                 metrics.status === 'Scale' ? 'bg-emerald-500' : 'bg-red-500'
                             }`}
                             style={{ width: `${Math.min(metrics.ltvCacRatio * 15, 100)}%` }}
                          ></div>
                      </div>
                      
                      <div className="mt-4 flex justify-between items-center">
                          <span className="text-xs text-slate-400">Ratio</span>
                          <span className={`text-2xl font-mono font-bold ${
                              metrics.status === 'Star' ? 'text-yellow-400' : 
                              metrics.status === 'Scale' ? 'text-emerald-400' : 'text-red-400'
                          }`}>{metrics.ltvCacRatio.toFixed(2)}</span>
                      </div>
                  </div>
               </div>
            </div>

            {/* 2. Visual Profit Stack (The "Payback" timeline) */}
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h3 className="text-xs font-bold uppercase text-slate-500 mb-6 flex items-center gap-2">
                    <TrendingUp className="w-4 h-4" /> The Payback Path
                </h3>
                
                <div className="flex items-end gap-2 h-32 border-b border-slate-700 pb-2 overflow-x-auto">
                    {[1, 2, 3, 4, 5, 6].map((orderNum) => {
                        const cumulativeProfit = (orderNum * (aov * profitMargin/100)) - cac;
                        const isBreakeven = orderNum === metrics.paybackOrder;
                        return (
                            <div key={orderNum} className="flex-1 flex flex-col justify-end items-center group relative">
                                <div 
                                    className={`w-full rounded-t transition-all ${
                                        cumulativeProfit >= 0 ? 'bg-emerald-500/50 group-hover:bg-emerald-500' : 'bg-red-500/50 group-hover:bg-red-500'
                                    }`}
                                    style={{ height: `${Math.min(Math.abs(cumulativeProfit)/metrics.netLTV * 100, 100)}%` }}
                                ></div>
                                <span className="text-[10px] text-slate-500 mt-2">Order {orderNum}</span>
                                
                                {/* Tooltip Value */}
                                <span className={`absolute -top-6 text-[10px] font-bold ${cumulativeProfit >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                                    {fmt(cumulativeProfit)}
                                </span>
                            </div>
                        )
                    })}
                </div>
                <div className="mt-4 text-xs text-slate-400 flex items-center gap-2">
                    <ArrowRight className="w-4 h-4" />
                    You break even on <b className="text-white">Order #{metrics.paybackOrder}</b>. 
                    {metrics.paybackOrder === 1 ? " Instant Profit!" : " You must retain them to make money."}
                </div>
            </div>

            {/* 3. NEW: Cohort Scaling Simulator */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Cohort Output */}
                <div className="bg-indigo-900/10 border border-indigo-900/30 rounded-xl p-6 relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-4 opacity-10">
                        <Rocket className="w-24 h-24 text-indigo-500" />
                    </div>
                    <h3 className="text-xs font-bold uppercase text-indigo-400 mb-4 flex items-center gap-2">
                        <BarChart4 className="w-4 h-4" /> Cohort Forecast
                    </h3>
                    <div className="space-y-4 relative z-10">
                        <div>
                            <span className="text-xs text-slate-400 block">With a {fmt(monthlyAdBudget)} budget, you acquire:</span>
                            <span className="text-2xl font-bold text-white">{metrics.acquiredCustomers} New Customers</span>
                        </div>
                        <div className="w-full h-px bg-indigo-900/50"></div>
                        <div>
                            <span className="text-xs text-slate-400 block">Future Net Profit from this Batch:</span>
                            <span className="text-2xl font-bold text-emerald-400">{fmt(metrics.cohortProfit)}</span>
                            <p className="text-[10px] text-slate-500 mt-1">ROI: {metrics.roiPercentage.toFixed(0)}% on ad spend</p>
                        </div>
                    </div>
                </div>

                {/* Sensitivity & Strategy */}
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-between">
                    <div>
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-4 flex items-center gap-2">
                            <Microscope className="w-4 h-4" /> Growth Sensitivity
                        </h3>
                        <div className="space-y-3">
                            <div className="flex justify-between items-center text-xs">
                                <span className="text-slate-400">If Price increases 10%:</span>
                                <span className="text-emerald-400 font-bold">+{fmt(metrics.impactAov)} Profit</span>
                            </div>
                            <div className="flex justify-between items-center text-xs">
                                <span className="text-slate-400">If Frequency increases 10%:</span>
                                <span className="text-emerald-400 font-bold">+{fmt(metrics.impactFreq)} Profit</span>
                            </div>
                        </div>
                    </div>
                    
                    <div className="mt-4 p-3 rounded bg-slate-950 border border-slate-800">
                        <div className="flex items-center gap-2 mb-1">
                            <Crown className="w-4 h-4 text-yellow-500" />
                            <span className="text-xs font-bold text-white">Winner's Rule</span>
                        </div>
                        <p className="text-[10px] text-slate-500 leading-tight">
                            "He who can afford to spend the most to acquire a customer, wins."
                            Increase LTV so you can outbid competitors on ads.
                        </p>
                        {/* --- CREATOR FOOTER START --- */}
        <div className="mt-12 flex flex-col items-center justify-center space-y-2 border-t border-slate-800 pt-8">
          <p className="text-slate-500 font-medium text-sm">Created by SmartRwl</p>
          <div className="flex space-x-4">
            {/* Instagram Icon */}
            <a
              href="http://www.instagram.com/smartrwl"
              target="_blank"
              rel="noopener noreferrer"
              className="text-slate-600 hover:text-pink-500 transition-colors"
              title="Instagram"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
              </svg>
            </a>

            {/* GitHub Icon */}
            <a
              href="https://github.com/Smart-rwl/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-slate-600 hover:text-white transition-colors"
              title="GitHub"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
              </svg>
            </a>
          </div>
        </div>
        {/* --- CREATOR FOOTER END --- */}
                    </div>
                </div>

            </div>

          </div>

        </div>
      </div>
    </div>
  );
}